### ISSUE TITLE
Consider differentiating classes of software within Software Inventory

### ISSUE THREAD

**Issue by adammontville** [sacmwg/draft-ietf-sacm-information-model#10]
This issue was raised during the 2015-04-17 endpoint ID design meeting.  Ron Colvin suggested that Operating System ought to be a primary identifying attribute rather than "buried" as a secondary attribute within Software Inventory.  There was some disagreement, but we eventually settled on OS not being a primary attribute for identification, but also recognized that OS could be, depending on operational context, more important than other types of software.  Should we provide for such a distinction within our information model?

**Comment by athiasjerome** [comment]
Mainly using OVAL and (AI) as a reference, and IMHO, OS should not be a primary attribute.
(if we would go otherwise, we would have to consider Firmware first)

**Comment by djhaynes** [comment]
There are currently OS-related IEs in the IM (e.g. osComponent, osLabel, osName, osType, osVersion) that came from the I-D IM.  Do we specifically want to call out OS-related information in this way?  Or, do we want to remove this OS-related information and expect that it will be covered by software-related IEs (e.g. softwareTitle, SoftwareCreator, softwareVersion, etc.)?

Thanks,

Danny

**Comment by sacm** [comment]
Hi Danny,

I urge that you keep the explicit OS attributes.  Sometimes (often?) you
don't
care about apps, but you always care about OS on an endpoint or middlebox.

Cheers,
- Ira

Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
Jan-April: 579 Park Place  Saline, MI  48176  734-944-0094
May-Dec: PO Box 221  Grand Marais, MI 49839  906-494-2434

**Comment by djhaynes** [comment]
Thanks for the feedback Ira!  Do others have thoughts on this topic?

Thanks,

Danny

**Comment by adammontville** [comment]
I would like the ability to understand when software is an operating system, but beyond that, I think adding "osLabel" and the like would be redundant.  I would expect we'd have "label" for software name.  It'd be rad to have a solid software classification system though.

**Comment by sacm** [comment]
Hi Adam,

I agree that it's important to tell that software is an OS.  Host Resource
MIB
(RFC 2790) and many other interfaces also distinguish drivers from other
non-OS
software (I also think this is important).

What level of granularity (or whatever) did you mean by a "solid software
classification system" goal?

Cheers,
- Ira

Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
Jan-April: 579 Park Place  Saline, MI  48176  734-944-0094
May-Dec: PO Box 221  Grand Marais, MI 49839  906-494-2434

**Comment by adammontville** [comment]
I don't know what one should look like, but if in the IM we have the notion of "software" with proper classification, it seems (I could be wrong) that we would need fewer one-off attribute names (i.e. "firmwareLabel", "osLabel", and so on.  We would in effect say, "this is a software instance of class 'operating system'".  We might take that classification system further to say, "this is a software instance of class 'Windows operating system'".   We might additionally be able to classify things like "RTOS" is-a "Operating System" and know that when we see "ChronOS" we're dealing with a real-time OS because "ChronOS" is-a "RTOS" is-a "Operating System".

I'm not sure that goes toward answering your question, though.

**Comment by sacm** [comment]
Hi Adam,

Very good answer.  I like this progressive refinement from OS to RTOS to
ChronOS.  And I like generic attributes like softwareLabel, softwareClass,
and so on.

By adroit cherry picking from DMTF CIM (WMI, etc.) software schema,
I think we could achieve a fair amount of this and perhaps also benefit by
the very large number of DMTF-registered values for various attributes
rather than trying to use the several poorly maintained equivalent IANA
registries.

Cheers,
- Ira

Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
Jan-April: 579 Park Place  Saline, MI  48176  734-944-0094
May-Dec: PO Box 221  Grand Marais, MI 49839  906-494-2434

**Comment by djhaynes** [comment]
Here's a link to the DMTF SoftwareIdentity model (http://schemas.dmtf.org/wbem/cim-html/2.41.0+/CIM_SoftwareIdentity.html).  It contains a "classifications" attribute that distinguishes between operating systems, applications, firmware, etc.

So, it sounds like if we have a way to distinguish between operating systems, applications, firmware, etc., we could remove these OS-related attributes?

As a side note, I also came across a DMTF CIM profile for SWID tags (https://www.dmtf.org/sites/default/files/standards/documents/DSP1067_1.0.0.pdf) which may be of interest to the WG.

**Comment by sacm** [comment]
We have had to worry about _where_ an application is installed.  For example, in our software inventory tool-for Windows devices, we have to look in the uninstall registry, in the windows application store, and in the Windows "features" to find installed software.    We will also begin collecting executables that are mapped to file extensions which act as installed software, but aren't formally "installed."  We also want to find browser plugins and extensions since they are software installed in software--and commonly have vulnerabilities.

It seems like a classification system may need to be able to differentiate between the "types" of software, to some extent.

The other issue we recently ran up against is trying to identify web sites and pages and database instances.  Not so much because we really think web pages and database instances are "software" per se, but they behave a lot like software with respect to needing to be securely configured and being able to contain vulnerabilities based on running vulnerable code.

Joseph L. Wolfkiel
SCM Engineering Lead
DISA ID52
Fort Meade DISA Acquisiton Bldg Cube A4A58E
Work: (301) 225-8820
Gov Cell: (571) 814-8231
Joseph.L.Wolfkiel.civ@mail.mil

-----Original Message-----
From: sacm [mailto:sacm-bounces@ietf.org] On Behalf Of Danny Haynes
Sent: Monday, November 07, 2016 6:10 AM
To: sacmwg/draft-ietf-sacm-information-model
Cc: Comment; sacm
Subject: [Non-DoD Source] Re: [sacm] [sacmwg/draft-ietf-sacm-information-model] Consider differentiating classes of software within Software Inventory (#10)

All active links contained in this email were disabled. Please verify the identity of the sender, and confirm the authenticity of all links contained within the message prior to copying and pasting the address to a Web browser. 

---

Here's a link to the DMTF SoftwareIdentity model (Caution-http://schemas.dmtf.org/wbem/cim-html/2.41.0+/CIM_SoftwareIdentity.html < Caution-http://schemas.dmtf.org/wbem/cim-html/2.41.0+/CIM_SoftwareIdentity.html > ). It contains a "classifications" attribute that distinguishes between operating systems, applications, firmware, etc.

So, it sounds like if we have a way to distinguish between operating systems, applications, firmware, etc., we could remove these OS-related attributes?

As a side note, I also came across a DMTF CIM profile for SWID tags (Caution-https://www.dmtf.org/sites/default/files/standards/documents/DSP1067_1.0.0.pdf < Caution-https://www.dmtf.org/sites/default/files/standards/documents/DSP1067_1.0.0.pdf > ) which may be of interest to the WG.

**Comment by cliffordk** [comment]
At the risk of coming from left field …

It may be worthwhile to model what privileges the software runs with. Software that runs with elevated privileges (higher than the user invoking it or giving it input) is subject to more vulnerabilities. Conversely, software that runs in a sandbox or container, with less privilege than the user, is subject to fewer vulnerabilities.

This privilege question is often an attribute of the software, but sometimes it is a matter of how the software is run.

Best,
                                                Cliff

**Comment by djhaynes** [comment]
Hi Cliff,

I agree privilege is definitely something we want to consider. However, I think we may want to separate it out from software inventory.  For example, one approach might be to cover it under the configuration of that software on an endpoint (e.g. looking at how a service is configured, or how a process is running, etc.).  

Thanks,

Danny

**Comment by sacm** [comment]
Hi Cliff,

Good point about the execution privileges of software.  Usually not
collected,
but very important info for assessing the actual risk to the monitored
system.

Cheers,
- Ira

Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
Jan-April: 579 Park Place  Saline, MI  48176  734-944-0094
May-Dec: PO Box 221  Grand Marais, MI 49839  906-494-2434

**Comment by djhaynes** [comment]
Hi Cliff,

I agree privilege is definitely something we want to consider. However, I think we may want to separate it out from software inventory. For example, one approach might be to cover it under the configuration of that software on an endpoint (e.g. looking at how a service is configured, or how a process is running, etc.).

Thanks,

Danny

**Comment by djhaynes** [comment]
During the IETF 97 SACM session, one member gave a +1 for the generic software subject with a class attribute and another member said just pick one and go.  Given that feedback and the feedback in the GitHub issue, I will go ahead and add a class attribute to the generic software instance subject (using values from CIM software identity and RFC2790) as well as remove the attributes specific to a type of software.
